### ISSUE TITLE
Object has no attribute 'row_attrs'

### ISSUE THREAD

**Issue by Ping-lin14** [MissionBio/mosaic#8] opened 2021-12-05 09:13 UTC
Hi. I am very grateful that you have solved the problem of merging samples for me, but soon I encountered new obstacles.
Error`AttributeError: 'Sample' object has no attribute 'barcodes'` when I select all cells and final variants again.
So I check the sample message and found that my sample does not have `row_attrs`
```
sample.row_attrs
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_268042/15318339.py in <module>
----> 1 sample.row_attrs

AttributeError: 'Sample' object has no attribute 'row_attrs'
```
What should I do?

**Comment by KKJSP** [comment] 2021-12-05 20:24
@Ping-lin14 `Sample` does not have the attribute `row_attrs`. Are you looking for `sample.dna.row_attrs` or `sample.dna.barcodes()`?

Please go through the documentation and available vignettes linked in the [README](https://github.com/MissionBio/mosaic) to see how mosaic works. If you require further assistance with your specific problem, you can contact the support team at support@missionbio.com

I'm closing this issue, since it's not a bug.

**Closed as completed by KKJSP** 2021-12-05 20:24 UTC
